name: CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo 'Building the project...'
          # Add actual build commands here

      - name: Test
        run: |
          echo 'Running tests...'
          # Add actual test commands here

      - name: Deploy
        run: |
          echo 'Deploying the project...'
          # Add actual deployment commands here
